### ISSUE TITLE
kaios 2.5 how to enable developer option. 

### ISSUE THREAD

**Issue by varundtsfi** [Orange-OpenSource/minikey#1]
It's not androdi, How adb will work for that. Or some other sdk I have to setup on my environment.
Or how this file comunicate with device . It's not android so how adb will work 
Any Suggestion?_

**Comment by jmauffret** [comment]
On my Nokia 8110,  I just press *#*#33284#*#* to activate/deactivate the Debug mode.
When Debug mode activated you will see a "bug status" icon on top of screen.
BR

**Comment by varundtsfi** [comment]
> On my Nokia 8110, I just press _#_#33284#_#_ to activate/deactivate the Debug mode.
> When Debug mode activated you will see a "bug status" icon on top of screen.
> BR

Then I have to buy the Same device but  there could be a generic solution to enable developer option in all the KaiOS Devices like in android or ios devices.

I have found few information on KaiOS helper site might be helpful for others.

https://developer.kaiostech.com/getting-started/env-setup/os-env-setup

**Comment by varundtsfi** [comment]
> On my Nokia 8110, I just press _#_#33284#_#_ to activate/deactivate the Debug mode.
> When Debug mode activated you will see a "bug status" icon on top of screen.
> BR

Hi @jmauffret  ,

For me above code is not working  just dial the **#**#33284#**#**

**Comment by varundtsfi** [comment]
> On my Nokia 8110, I just press _#_#33284#_#_ to activate/deactivate the Debug mode.
> When Debug mode activated you will see a "bug status" icon on top of screen.
> BR

hi @jmauffret  Your code to enable the debug mode is working fine sir Only problem is on UI of github star is not displayed on UI.

That's why I have attached the image for that.
![Screenshot from 2019-08-30 16-36-27](https://user-images.githubusercontent.com/16011730/64016341-60936d80-cb44-11e9-81a0-9cf098b6951d.png)
 Thanks a lot sir.

**Comment by marko-radojcic** [comment]
Worked for me on Nokia 8110 4G
